name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: swift-format lint --recursive --strict --parallel .
      - name: Build
        run: swift build
      - name: Test
        run: swift test
